"""empty message

Revision ID: 0fbeb95f4ffa
Revises: 38d250f1db53
Create Date: 2018-11-10 12:05:31.675078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fbeb95f4ffa'
down_revision = '38d250f1db53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('girls_img', sa.Column('img_status', sa.Integer(), nullable=False))
    op.add_column('girls_img', sa.Column('init_url', sa.String(length=48), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('girls_img', 'init_url')
    op.drop_column('girls_img', 'img_status')
    # ### end Alembic commands ###
