"""empty message

Revision ID: 168af717e1bd
Revises: 51aefa574d37
Create Date: 2018-11-06 14:42:31.600339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168af717e1bd'
down_revision = '51aefa574d37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('create_data', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'create_data')
    # ### end Alembic commands ###
