"""empty message

Revision ID: 38d250f1db53
Revises: a7399db6814a
Create Date: 2018-11-10 11:48:23.358324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d250f1db53'
down_revision = 'a7399db6814a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('girls_img',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('img_path', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('img_path')
    )
    op.create_table('girls_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('tag', sa.String(length=48), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    op.create_table('girls_album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('cover_img', sa.String(length=256), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('girls_tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['girls_tag_id'], ['girls_tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('girls_album')
    op.drop_table('girls_tag')
    op.drop_table('girls_img')
    # ### end Alembic commands ###
