"""empty message

Revision ID: 4ce5e369441a
Revises: 0fbeb95f4ffa
Create Date: 2018-11-10 17:49:08.990873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ce5e369441a'
down_revision = '0fbeb95f4ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('girls_tag', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=256),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('girls_tag', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=256),
               nullable=False)
    # ### end Alembic commands ###
