"""empty message

Revision ID: 51aefa574d37
Revises: 6d1b319293c8
Create Date: 2018-11-06 11:03:18.698726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51aefa574d37'
down_revision = '6d1b319293c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'category', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='unique')
    # ### end Alembic commands ###
