"""empty message

Revision ID: 6d1b319293c8
Revises: 12cdae3f0372
Create Date: 2018-11-01 19:19:12.257600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d1b319293c8'
down_revision = '12cdae3f0372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=12), nullable=True),
    sa.Column('isDelete', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('articles', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('articles', sa.Column('isDelete', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'articles', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'isDelete')
    op.drop_column('articles', 'category_id')
    op.drop_table('category')
    # ### end Alembic commands ###
