"""empty message

Revision ID: 87116ea7625a
Revises: 
Create Date: 2018-10-30 09:42:36.531802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87116ea7625a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=32), server_default='', nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('nickname', sa.String(length=24), nullable=False),
    sa.Column('login_time', sa.Integer(), nullable=True),
    sa.Column('headshot', sa.String(length=128), nullable=True),
    sa.Column('_password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
