"""empty message

Revision ID: a7399db6814a
Revises: 3328bfdcce95
Create Date: 2018-11-08 11:05:55.212588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7399db6814a'
down_revision = '3328bfdcce95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('real_avatar', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'real_avatar')
    # ### end Alembic commands ###
