"""empty message

Revision ID: bb6b5d7923e4
Revises: ee2cc7132595
Create Date: 2018-10-30 09:43:55.827689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb6b5d7923e4'
down_revision = 'ee2cc7132595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('field1', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'field1')
    # ### end Alembic commands ###
